# DO NOT EDIT THIS FILE
#
# Please edit /boot/uEnv.txt to set supported parameters
#

setenv load_addr "0x05000000"
setenv overlay_error "false"
# default values
setenv overlay_prefix "rockchip"
setenv verbosity "1"
setenv console " "
setenv rootfstype "ext4"
setenv docker_optimizations "off"

echo "Boot script loaded from ${devtype} ${devnum}"

if test -e ${devtype} ${devnum}:1 ${prefix}uEnv.txt; then
	load ${devtype} ${devnum}:1 ${load_addr} ${prefix}uEnv.txt
	env import -t ${load_addr} ${filesize}
fi

setenv bootargs "console=tty1 console=${console} rw root=PARTUUID=${rootuuid} rootfstype=${rootfstype} init=/sbin/init rootwait"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"; fi

load ${devtype} ${devnum}:1 ${kernel_addr_r} ${prefix}${kernelimg}

bootm ${kernel_addr_r}
# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
